export const TYPES = {
  INC_SESSION: 'INC_SESSION',
  DEC_SESSION: 'DEC_SESSION',
  INC_BREAK: 'INC_BREAK',
  DEC_BREAK: 'DEC_BREAK',
  DEC_SECONDS: 'DEC_SECONDS',
  
  SWITCH_SESSION: 'SWITCH_SESSION',
  SWITCH_BREAK: ' SWITCH_BREAK',

  START_TIMER: 'START_TIMER',
  STOP_TIMER: 'STOP_TIMER',
  RESET_TIMER: 'RESET_TIMER'
};